nelmio_security:
    forced_ssl:
        hsts_max_age: 31536000
        hsts_subdomains: true
        hsts_preload: true


    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
          

    csp:
        enabled: true
        enforce:
            # see full description below
            level1_fallback: true
            # only send directives supported by the browser, defaults to false
            # this is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive:
                enabled: false
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src: [ 'self', "https://www.ecole-richard-cross.com" ]
            frame-src: [ 'none' ]
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://cdn.jsdelivr.net'
                - 'https://unpkg.com'
            img-src:
                - 'self'
                - 'https://www.ecole-richard-cross.com'
                - 'https://unpkg.com'
                - 'data:'
                - 'blob:'
            style-src: 
                - 'self'
                - 'unsafe-inline'
                - 'https://cdn.jsdelivr.net'
                - 'https://unpkg.com'
            
            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            object-src:  ['none']
            form-action:  ['self']
            base-uri:  ['self']
            frame-ancestors:  ['none']
