twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: 
        - "bootstrap_5_layout.html.twig"
        - 'form/TrixEditorType.html.twig'
        - 'form/TagSelectType.html.twig'
    globals:
        socials:
            instagram:
                url: https://www.instagram.com/ecole.richard.cross/
                iconUrl: https://www.ecole-richard-cross.com/img/icons/logo-instagram.png
                altText: "Lien vers le compte Instagram de l'Ecole"
            twitter:
                url: https://twitter.com/EcoleCross
                iconUrl: https://www.ecole-richard-cross.com/img/icons/logo-twitter.png
                altText: "Lien vers le compte Twitter de l'Ecole"
            linkedin:
                url: "https://www.linkedin.com/company/école-richard-cross/"
                iconUrl: https://www.ecole-richard-cross.com/img/icons/logo-linkedin.png
                altText: "Lien vers le compte LinkedIn de l'Ecole"
            facebook:
                url: https://www.facebook.com/ecolerichardcross
                iconUrl: https://www.ecole-richard-cross.com/img/icons/logo-facebook.png
                altText: "Lien vers le compte Facebook de l'Ecole"
            youtube:
                url: https://www.youtube.com/c/ecolerichardcross/
                iconUrl: https://www.ecole-richard-cross.com/img/icons/logo-youtube.png
                altText: "Lien vers le compte YouTube de l'Ecole"

when@test:
    twig:
        strict_variables: true
